// SPDX-FileCopyrightText: 2024-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace DragonLib.SourceGen;

[Generator]
public class BitStructGenerator : IIncrementalGenerator {
	public void Initialize(IncrementalGeneratorInitializationContext context) {
		var source = context.SyntaxProvider.ForAttributeWithMetadataName(
			"DragonLib.SourceGen.BitStructGenerator.BitStructAttribute",
			static (node, _) => node is StructDeclarationSyntax,
			static (ctx, _) => (INamedTypeSymbol) ctx.TargetSymbol);

		context.RegisterSourceOutput(source, static (spc, symbol) => {
			var typeAttribute = symbol.GetAttributes().First(x => x is { AttributeClass.Name: "BitStructAttribute" } && x.ConstructorArguments[0].Value is int);
			var size = (int) typeAttribute.ConstructorArguments[0].Value!;

			var sb = new StringBuilder();
			sb.AppendLine("/// <auto-generated/>");
			sb.AppendLine();
			sb.AppendLine("using System.Runtime.CompilerServices;");
			sb.AppendLine("using System.Runtime.InteropServices;");
			sb.AppendLine();
			sb.AppendLine($"namespace {symbol.ContainingNamespace.ToDisplayString()};");
			sb.AppendLine();

			sb.AppendLine($"[InlineArray({size})]");
			sb.AppendLine($"public partial struct {symbol.Name} : IEquatable<{symbol.Name}> {{");
			sb.AppendLine("\tprivate byte Value { get; set; }");
			sb.AppendLine();
			sb.AppendLine($"\tpublic override bool Equals(object obj) => obj is {symbol.Name} other && Equals(other);");
			sb.AppendLine($"\tpublic bool Equals({symbol.Name} other) => ((ReadOnlySpan<byte>) this).SequenceEqual((ReadOnlySpan<byte>) other);");
			sb.AppendLine($"\tpublic bool Equals(in {symbol.Name} other) => ((ReadOnlySpan<byte>) this).SequenceEqual((ReadOnlySpan<byte>) other);");
			sb.AppendLine($"\tpublic static bool operator ==(in {symbol.Name} left, in {symbol.Name} right) => left.Equals(in right);");
			sb.AppendLine($"\tpublic static bool operator !=(in {symbol.Name} left, in {symbol.Name} right) => !(left == right);");
			sb.AppendLine("\tpublic override int GetHashCode() { var hc = new HashCode(); hc.AddBytes((ReadOnlySpan<byte>) this); return hc.ToHashCode(); }");

			var shift = 0;
			foreach (var property in symbol.GetMembers().OfType<IPropertySymbol>()) {
				var bitFieldAttribute = property.GetAttributes().FirstOrDefault(x => x.AttributeClass?.Name == "BitFieldAttribute" && x.ConstructorArguments[0].Value is int);
				if (bitFieldAttribute == default) {
					continue;
				}

				var type = property.Type.ToDisplayString();
				var bits = (int) bitFieldAttribute.ConstructorArguments[0].Value!;
				var mask = bits == 64 ? ulong.MaxValue : (1ul << bits) - 1ul;
				var startByte = shift / 8;
				var endByte = (shift + bits - 1) / 8;
				var bitOffset = shift % 8;
				var signBits = type switch {
					"sbyte" => 8,
					"short" => 16,
					"int" => 32,
					"long" => 64,
					_ => 0,
				};

				sb.AppendLine();
				sb.AppendLine($"\tpublic partial {type} {property.Name} {{");

				// todo: drop empty shifts (<< 0 and >> 0)
				sb.AppendLine("\t\tget {");
				sb.AppendLine("\t\t\tvar value = 0ul;");
				for (var i = startByte; i <= endByte; i++) {
					var byteShift = (i - startByte) * 8;
					sb.AppendLine($"\t\t\tvalue |= (ulong) this[{i}] << {byteShift};");
				}

				if (signBits == 0) {
					sb.AppendLine($"\t\t\treturn ({type}) ((value >> {bitOffset}) & 0x{mask:x}ul);");
				} else {
					var shiftAmount = signBits - bits;
					sb.AppendLine($"\t\t\tvar raw = (value >> {bitOffset}) & 0x{mask:x}ul;");
					sb.AppendLine($"\t\t\treturn ({type}) ((({type}) (raw << {shiftAmount})) >> {shiftAmount});");
				}

				sb.AppendLine("\t\t}");

				sb.AppendLine("\t\tset {");
				sb.AppendLine($"\t\t\tvar val = ((ulong) value & 0x{mask:x}ul) << {bitOffset};");
				// todo: mask can be dropped only needed for first and last copy
				sb.AppendLine($"\t\t\tvar mask = 0x{mask:x}ul << {bitOffset};");
				for (var i = startByte; i <= endByte; i++) {
					var byteShift = (i - startByte) * 8;
					sb.AppendLine($"\t\t\tthis[{i}] = (byte) ((this[{i}] & ~(mask >> {byteShift})) | ((val >> {byteShift}) & 0xff));");
				}

				sb.AppendLine("\t\t}");
				sb.AppendLine("\t}");

				shift += bits;
			}

			sb.AppendLine("}");
			spc.AddSource($"{symbol.Name}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
		});
	}
}
