// SPDX-FileCopyrightText: 2024-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace DragonLib.SourceGen;

[Generator]
public class MagicGenerator : IIncrementalGenerator {
	public void Initialize(IncrementalGeneratorInitializationContext context) {
		var source = context.SyntaxProvider.ForAttributeWithMetadataName(
			"DragonLib.SourceGen.MagicGenerator.GenerateMagicAttribute",
			static (node, _) => node is ClassDeclarationSyntax,
			static (ctx, _) => (INamedTypeSymbol) ctx.TargetSymbol);

		context.RegisterSourceOutput(source, static (spc, symbol) => {
			var sb = new StringBuilder();
			sb.AppendLine("/// <auto-generated/>");
			sb.AppendLine();
			sb.AppendLine($"namespace {symbol.ContainingNamespace.ToDisplayString()};");
			sb.AppendLine();
			sb.AppendLine($"public partial class {symbol.Name} {{");

			foreach (var property in symbol.GetMembers().OfType<IPropertySymbol>()) {
				var magicAttribute = property.GetAttributes().FirstOrDefault(x => x.AttributeClass?.Name == "MagicAttribute" && x.ConstructorArguments is [{ Value: string }]);
				if (magicAttribute == default) {
					continue;
				}

				var magic = (string) magicAttribute.ConstructorArguments[0].Value!;
				// todo: validate value fits in type
				var value = 0ul;
				for (var i = 0; i < magic.Length; i++) {
					value |= (ulong) (byte) magic[i] << (i * 8);
				}

				sb.AppendLine($"\tpublic partial {property.Type.ToDisplayString()} {property.Name} => 0x{value:x}u;");
			}

			sb.AppendLine("}");
			spc.AddSource($"{symbol.Name}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
		});
	}
}
