<!--
SPDX-FileCopyrightText: 2025 Legiayayana

SPDX-License-Identifier: EUPL-1.2
-->

<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>enable</Nullable>
		<LangVersion>preview</LangVersion>
		<TargetFrameworks>net8.0;net9.0</TargetFrameworks>
	</PropertyGroup>

</Project>
